### PR TITLE
initialized file structure and files

### PR DESCRIPTION
**Pull request by abbynf**
Issue 1

### CODE REVIEW

**Review by Feizhi255 — APPROVED** [review]
looks great good job!

**Comment by jburz** [comment]
It looks pretty good!  The only thing I can see is it looks like the eslint was removed from the package.json.  We probably want to keep that in there.

**Comment by abbynf** [comment]
@jburz  I will add the ESLint in the package.json, thank you for catching that! I can see it in the "scripts" section and the "devDependencies" section. Where else does it go?

**Comment by jburz** [comment]
As long as it has been installed then the package.json dependency should auto update.  It would need to be added manually as a script.

**Review by jburz — COMMENTED** [review]
5 gold stars!

**Review by jburz — APPROVED** [review]

**Pull request merged**
